# Generated by Django 5.1.5 on 2025-02-08 09:41

from django.db import migrations

def populate_entryid(apps, schema_editor):
    TodoEntry = apps.get_model('projet1', 'TodoEntry')
    User = apps.get_model('auth', 'User')

    # Iterate over all users
    for user in User.objects.all():
        # Get all entries for the user, ordered by dateCreated
        entries = TodoEntry.objects.filter(user=user).order_by('dateCreated')
        
        # Assign entryid starting from 1
        for index, entry in enumerate(entries, start=1):
            entry.entryid = index
            entry.save()

class Migration(migrations.Migration):
    dependencies = [
        ('projet1', '0002_alter_todoentry_datecreated_token'),
    ]

    operations = [
        migrations.RunPython(populate_entryid),
    ]