# Generated by Django 5.1.5 on 2025-02-08 09:48

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet1', '0003_auto_20250208_1041'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='todoentry',
            name='entryid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='todoentry',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='todoentry',
            constraint=models.UniqueConstraint(fields=('user', 'entryid'), name='unique_user_entryid'),
        ),
    ]
