# Generated by Django 5.1.5 on 2025-02-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet1', '0004_todoentry_entryid_alter_todoentry_datecreated_and_more'),
        ('projet1', '0007_todoentry_entryid_alter_todoentry_datecreated_and_more'),
    ]

    operations = [
    ]
